name: Build and Test ADC

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Nuitka, Pytest
        run: |
          python -m pip install --upgrade pip
          pip install nuitka pytest

      - name: Compile with Nuitka
        run: |
            nuitka src/ADC_Archiver_1.2.0.py --standalone --onefile --output-dir=build


      - name: Run tests
        run: |
          pytest tests/
# (c) 2025 Mealman1551
# This file is part of ADC Archiver 1.2.0 in Main branch.
# ADC Archiver 1.2.0 is free software: you can redistribute it and/or modify
