name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.email "nathandubuy4@gmail.com"
          git config --global user.name "Mealman1551"

          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/Mealman1551/ADC.git
          git push --mirror gitlab
