name: Sync to GitLab

on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          fetch-tags: true

      - name: Configure git
        run: |
          git config --global user.email "nathandubuy4@gmail.com"
          git config --global user.name "Mealman1551"

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/Mealman1551/ADC.git
          git remote set-head gitlab -d
          git fetch --all
          git push gitlab --all
          git push gitlab --tags
